import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

{/* Reusable class for skill tags */}
<style jsx>{`
  .skill-chip {
    @apply px-3 py-1 text-xs font-medium
    bg-neutral-100 dark:bg-neutral-800
    border border-neutral-200 dark:border-neutral-700
    rounded-full text-neutral-700 dark:text-neutral-300;
  }
`}</style>


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tchamna Shck - AI Engineer & Data Scientist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Pre-hydration script: apply user's saved theme or default to dark before React mounts
          This avoids flash-of-incorrect-theme on first paint and ensures the site defaults to
          dark mode when no explicit user preference is stored. */}
      <script
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: `try{const t=localStorage.getItem('theme');if(t==='dark')document.documentElement.classList.add('dark');else if(t==='light')document.documentElement.classList.remove('dark');else document.documentElement.classList.add('dark');}catch(e){}` }}
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
